'use strict';
// Independent controls, excluded from the eight-episode metric.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),Module=require('node:module'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'../..'),source=fs.readFileSync(path.join(root,'index.html'),'utf8'),rows=[];
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures-v1.json'))),clone=x=>JSON.parse(JSON.stringify(x));
function check(name,fn){try{fn();rows.push({name,status:'PASS'});}catch(e){rows.push({name,status:'FAIL',error:e.message});}}
const helper=source.slice(source.indexOf('function topsReadProgressArray('),source.indexOf('function App()'));
assert(helper.includes('function topsRestoreDocuments'));
function hydrate(storage,getThrows=false){const ctx={TRANSITION_MILESTONES:clone(fixture.canonical.milestones),DOCUMENT_VAULT:clone(fixture.canonical.documents),window:{__IS_IFRAME:false,__safeGet:k=>{if(getThrows)throw Error('Storage denied');return storage[k]??null;}}};vm.createContext(ctx);vm.runInContext(helper+';result={milestones:topsRestoreMilestones(),documents:topsRestoreDocuments()};',ctx);return clone(ctx.result);}
const defaults={milestones:fixture.canonical.milestones,documents:fixture.canonical.documents};
for(const [name,storage] of [['absent',{}],['invalid JSON',{taskProgress:'{',docProgress:'['}],['wrong shape',{taskProgress:'{}',docProgress:'null'}],['non-array tasks',{taskProgress:'[{"id":1,"tasks":{}}]',docProgress:'[null,7,"x"]'}],['non-boolean',{taskProgress:'[{"id":1,"tasks":[{"id":"t1","done":"true"}]}]',docProgress:'[{"id":"d1","obtained":1}]'}]])check(name,()=>assert.deepEqual(hydrate(storage),defaults));
check('storage reads unavailable',()=>assert.deepEqual(hydrate({},true),defaults));
check('duplicates: first valid boolean wins, including false',()=>{const s=hydrate({taskProgress:'[{"id":1,"tasks":[{"id":"t1","done":false},{"id":"t1","done":true}]},{"id":1,"tasks":[{"id":"t1","done":true}]}]',docProgress:'[{"id":"d1","obtained":false},{"id":"d1","obtained":true}]'});assert.deepEqual(s,defaults);});
check('removed IDs ignored, omitted/new canonical IDs default, strict milestone ID type',()=>{const s=hydrate({taskProgress:'[{"id":"1","tasks":[{"id":"t1","done":true}]},{"id":1,"tasks":[{"id":"removed","done":true},{"id":"t3","done":true}]}]',docProgress:'[{"id":"removed","obtained":true},{"id":"d12","obtained":true}]'});const e=clone(defaults);e.milestones[0].tasks.find(t=>t.id==='t3').done=true;e.documents[11].obtained=true;assert.deepEqual(s,e);});
check('corrupt keys isolated in both directions',()=>{let s=hydrate({taskProgress:'{',docProgress:'[{"id":"d1","obtained":true}]'});assert(s.documents[0].obtained);assert.deepEqual(s.milestones,defaults.milestones);s=hydrate({docProgress:'{',taskProgress:'[{"id":1,"tasks":[{"id":"t1","done":true}]}]'});assert(s.milestones[0].tasks[0].done);assert.deepEqual(s.documents,defaults.documents);});
check('meaning changes cannot be inferred from a stable ID',()=>{const s=hydrate({taskProgress:'[{"id":1,"tasks":[{"id":"t1","text":"DIFFERENT MEANING SENTINEL","done":true}]}]'});assert(s.milestones[0].tasks[0].done);assert.equal(s.milestones[0].tasks[0].text,defaults.milestones[0].tasks[0].text);});
// Replay the six earlier real-loader fixtures with the new initializer seam, unchanged expected values.
const earlier=JSON.parse(fs.readFileSync(path.join(__dirname,'restore-fixtures.json')));
for(const c of earlier.cases)check('earlier contract: '+c.name,()=>{const s=hydrate(c.storage);let dismissed=[];try{const d=JSON.parse(c.storage.dismissedNotifs||'null');if(Array.isArray(d))dismissed=d;}catch(e){}assert.deepEqual({...s,dismissed},c.expected);});

// Browser controls reuse the same raw-source server and outbound blocking infrastructure.
const runner=path.join(__dirname,'browser-episodes.cjs'),m=new Module(runner,module);m.filename=runner;m.paths=module.paths;
const src=fs.readFileSync(runner,'utf8');m._compile(src.slice(0,src.indexOf('\n(async()=>'))+'\nmodule.exports={h,app,result,ev,click,loaded,state,flags,set(c,o){client=c;origin=o;},row(r){activeRow=r;}};',runner);
const b=m.exports;let chrome,client,origin;
const ev=b.ev;
async function test(name,fn){try{await fn();rows.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){rows.push({name,status:'FAIL',error:e.message});console.log('FAIL '+name+': '+e.message);}}
async function seed(storage,extra=''){b.row({steps:[],activations:0});const r=await client.send('Page.addScriptToEvaluateOnNewDocument',{source:`localStorage.clear();for(const [k,v] of Object.entries(${JSON.stringify(storage)}))localStorage.setItem(k,v);${extra}`});await client.send('Page.navigate',{url:origin+'/?tool=dashboard'});await b.loaded();await client.send('Page.removeScriptToEvaluateOnNewDocument',{identifier:r.identifier});}
async function key(id,key='Enter'){await ev(`document.getElementById(${JSON.stringify(id)}).focus()`);await b.h.dispatchKey(client,key,0);await b.h.delay(100);}
async function home(){await b.click('HOME');}
async function focusIs(id){assert.equal(await ev('document.activeElement?.id'),id);}
async function ui(){const proxy=b.h.createBlockingProxy();try{origin='http://127.0.0.1:'+await b.h.listen(b.app);chrome=await b.h.launchChrome(b.h.findChrome(),await b.h.listen(proxy.server));client=chrome.client;b.set(client,origin);client.on('Fetch.requestPaused',e=>{const u=e.request.url,ok=u.startsWith(origin+'/')&&!u.includes('/.netlify/')||/^(about|blob|data):/.test(u);if(!ok)b.result.externalAttempts.push(u);client.send(ok?'Fetch.continueRequest':'Fetch.failRequest',ok?{requestId:e.requestId}:{requestId:e.requestId,errorReason:'BlockedByClient'}).catch(e=>b.result.exceptions.push(String(e)));});client.on('Runtime.exceptionThrown',e=>b.result.exceptions.push(e.exceptionDetails?.text));await Promise.all([client.send('Page.enable'),client.send('Runtime.enable'),client.send('Fetch.enable',{patterns:[{urlPattern:'*'}]})]);await client.send('Emulation.setTimezoneOverride',{timezoneId:fixture.timezone});await client.send('Page.addScriptToEvaluateOnNewDocument',{source:`const OD=Date;window.Date=class extends OD{constructor(...a){super(...(a.length?a:[${Date.parse(fixture.clock)}]));}static now(){return ${Date.parse(fixture.clock)};}};window.__testWrites=[];const os=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){window.__testWrites.push({key:k,value:String(v)});return os.call(this,k,v);};`});
await client.send('Emulation.setDeviceMetricsOverride',{...fixture.viewport,deviceScaleFactor:1,mobile:true});
await test('hydration: no transient completion clobber in any mount write',async()=>{for(const c of [fixture.cases[0],fixture.cases[4],fixture.cases[5]]){await seed(c.storage);const s=await b.state();for(const w of s.writes){if(w.key==='taskProgress')assert.deepEqual(b.flags({milestones:JSON.parse(w.value),documents:c.expected.documents}).milestones,b.flags(c.expected).milestones);if(w.key==='docProgress')assert.deepEqual(b.flags({milestones:c.expected.milestones,documents:JSON.parse(w.value)}).documents,b.flags(c.expected).documents);}}});
await test('native Home timeline/readiness focus and Home return',async()=>{await seed(fixture.cases[0].storage);for(const [id,target] of [['tops-home-timeline','tops-plan-timeline'],['tops-home-readiness','tops-plan-readiness']]){assert.equal(await ev(`document.getElementById('${id}').tagName`),'BUTTON');await key(id);await focusIs(target);await home();await focusIs(id);}});
await test('exact reminder clears blocking filters, replaces expanded target, native focus',async()=>{await seed(fixture.cases[3].storage);await key('tops-home-next-action');await focusIs('tops-reminder-r-18-res');await b.click('HEALTH');await b.click('CRITICAL');await home();await key('tops-home-next-action');await focusIs('tops-reminder-r-18-res');assert.equal(await ev("document.getElementById('tops-reminder-r-18-res').getAttribute('aria-expanded')"),'true');assert(await ev("document.body.innerText.includes('ACTION ITEMS')"));await home();await focusIs('tops-home-next-action');});
await test('same-day complete/reopen, counts, partial choice and Back without remount',async()=>{await seed(fixture.cases[0].storage);await key('tops-continue-milestone');await focusIs('tops-plan-milestone');await b.click(fixture.cases[0].text);await home();assert.equal(await ev("document.getElementById('tops-continue-milestone').innerText"),'Review timeline');await key('tops-continue-milestone');await b.click(fixture.cases[0].phase);await b.click(fixture.cases[0].text);await b.click('BACK TO TIMELINE');await home();assert((await ev("document.getElementById('tops-continue-milestone').innerText")).includes(fixture.cases[0].phase));await client.send('Page.reload',{ignoreCache:true});await b.loaded();assert.deepEqual(b.flags(await b.state()),b.flags(fixture.cases[0].expected));});
await test('first partial canonical order even when earlier milestone untouched',async()=>{const c=clone(fixture.cases[0]);c.expected.milestones.forEach(m=>m.tasks.forEach(t=>t.done=false));c.expected.milestones[2].tasks[0].done=true;c.expected.milestones[3].tasks[0].done=true;c.storage.taskProgress=JSON.stringify(c.expected.milestones);await seed(c.storage);assert((await ev("document.getElementById('tops-continue-milestone').innerText")).includes('9 Months Out'));});
await test('all complete and clean no-date states are honest; ordinary routes available',async()=>{await seed(fixture.cases[3].storage);assert.equal(await ev("document.getElementById('tops-continue-milestone').innerText"),'Review timeline');assert.equal(await ev("document.getElementById('tops-continue-documents').innerText"),'Review documents');const clean={tops_onboarded:'1',tops_user_status:'active'};await seed(clean);assert(await ev("document.body.innerText.includes('0/56 tasks complete; 0/12 documents obtained.')"));assert(!await ev("document.body.innerText.includes('SINCE YOUR LAST CHECK-IN')"));await key('tops-continue-documents');await focusIs('tops-plan-documents');});
await test('390/320/1280 Home and destination geometry, target size and focus',async()=>{for(const [width,height] of [[390,844],[320,640],[1280,720]]){await client.send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<500});await seed(fixture.cases[0].storage);for(const id of ['tops-continue-milestone','tops-continue-documents','tops-home-timeline','tops-home-readiness','tops-home-next-action']){const g=await ev(`(()=>{const e=document.getElementById('${id}');if(!e)return null;e.scrollIntoView({block:'center'});const r=e.getBoundingClientRect();return {w:r.width,h:r.height,left:r.left,right:r.right,hit:e.contains(document.elementFromPoint(r.left+r.width/2,r.top+r.height/2))};})()`);if(g){assert(g.w>=44&&g.h>=44,JSON.stringify(g));assert(g.left>=0&&g.right<=width+1,JSON.stringify(g));assert(g.hit,'pointer covered '+id);}}await key('tops-continue-documents');await focusIs('tops-plan-documents');assert(await ev('document.documentElement.scrollWidth<=innerWidth+1'));}});
await test('disabled storage loads canonical state, no save-success promise',async()=>{await seed({tops_onboarded:'1'},`Storage.prototype.getItem=function(){throw new DOMException('Unavailable','SecurityError')};Storage.prototype.setItem=function(){throw new DOMException('Unavailable','SecurityError')};`);if(await ev("document.body.innerText.includes('EXPLORE TOOLS FIRST')"))await b.click('EXPLORE TOOLS FIRST');assert(await ev("document.body.innerText.includes('0/56 tasks complete; 0/12 documents obtained.')"));assert(!await ev("document.body.innerText.includes('Successfully saved')"));});
await test('site-data clearing removes marks on cold load',async()=>{await seed(fixture.cases[0].storage);await ev('localStorage.clear()');await client.send('Page.reload',{ignoreCache:true});await b.loaded();if(await ev("document.body.innerText.includes('EXPLORE TOOLS FIRST')"))await b.click('EXPLORE TOOLS FIRST');assert(await ev("document.body.innerText.includes('0/56 tasks complete; 0/12 documents obtained.')"));});
await test('Guard/Reserve and spouse existing audience routes remain rendered',async()=>{for(const audience of ['guard','spouse','retired','separated']){await seed({...fixture.cases[0].storage,tops_user_status:audience});assert(await ev("!!document.querySelector('button')"));assert(!await ev("document.body.innerText.includes('OBSOLETE')"));if(audience==='guard')assert(!await ev("!!document.querySelector('#tops-continue-title')"));}});
check('no browser exception or local function call',()=>{assert.equal(b.result.exceptions.length,0);assert.equal(b.result.functionAttempts.length,0);assert(!b.result.externalAttempts.some(x=>/\.netlify|openai|onesignal|google-analytics|kit\.com/.test(x)));});
fs.writeFileSync(path.join(__dirname,'adverse-network.json'),JSON.stringify({externalAttempts:b.result.externalAttempts,exceptions:b.result.exceptions,functionAttempts:b.result.functionAttempts,proxyContacts:proxy.attempts.length},null,2)+'\n');
}finally{await b.h.stopChrome(chrome);await Promise.all([b.h.closeServer(b.app),b.h.closeServer(proxy.server)]);}}
ui().catch(e=>rows.push({name:'browser infrastructure',status:'FAIL',error:e.stack})).finally(()=>{const report={at:new Date().toISOString(),indexSha256:crypto.createHash('sha256').update(source).digest('hex'),metricDenominator:false,rows,pass:rows.filter(r=>r.status==='PASS').length,fail:rows.filter(r=>r.status==='FAIL').length,limits:'Synthetic automated controls, no manual AT. Stable IDs cannot establish completion after a meaning change; canonical ID governance still required.'};fs.writeFileSync(path.join(__dirname,'adverse.json'),JSON.stringify(report,null,2)+'\n');console.log(report.pass+' PASS / '+report.fail+' FAIL');process.exitCode=report.fail?1:0;});
