const reply=(status,data)=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store, max-age=0','CDN-Cache-Control':'no-store','Netlify-CDN-Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
export function plain(value,max=1200){
 if(typeof value!=='string')return '';
 return value.replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1\s*>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&(?:amp|lt|gt|quot|apos|nbsp);|&#(?:x[0-9a-f]+|\d+);/gi,x=>{const names={'&amp;':'&','&lt;':'<','&gt;':'>','&quot;':'"','&apos;':"'",'&nbsp;':' '};if(names[x.toLowerCase()])return names[x.toLowerCase()];const n=x[2].toLowerCase()==='x'?parseInt(x.slice(3,-1),16):parseInt(x.slice(2,-1),10);return n>31&&n<=0x10ffff?String.fromCodePoint(n):' ';}).replace(/<[^>]*>/g,' ').replace(/[\x00-\x1f\x7f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max);
}
export function officialURL(value){try{const u=new URL(value);if(u.protocol!=='https:'||u.hostname!=='www.usajobs.gov'||u.username||u.password||u.port||u.search||u.hash||!/^\/(?:job\/\d+|GetJob\/ViewDetails\/\d+)\/?$/i.test(u.pathname))return null;return u.href;}catch{return null;}}
async function readJSON(message,max){const reader=message.body?.getReader();if(!reader)throw Error('invalid');let size=0,chunks=[];try{for(;;){const {value,done}=await reader.read();if(done)break;size+=value.byteLength;if(size>max)throw Error('size');chunks.push(value);}}finally{reader.cancel().catch(()=>{});}const bytes=new Uint8Array(size);let pos=0;for(const c of chunks){bytes.set(c,pos);pos+=c.length;}return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));}
export function projectJobs(data,now){
 const rows=data?.SearchResult?.SearchResultItems;if(!Array.isArray(rows)||rows.length>10)throw Error('shape');let omitted=0,invalidLinks=0;const jobs=[];
 for(const item of rows){const d=item?.MatchedObjectDescriptor;if(!d||typeof d!=='object'||typeof d.PositionTitle!=='string')throw Error('shape');const url=officialURL(d.PositionURI);if(!url){omitted++;invalidLinks++;continue;}
 const rawClosing=plain(d.ApplicationCloseDate||d.PositionEndDate,80), day=rawClosing.slice(0,10);
 const validDay=/^\d{4}-\d{2}-\d{2}(?:T|$)/.test(rawClosing)&&Number.isFinite(Date.parse(day))&&new Date(day).toISOString().slice(0,10)===day;
 const closing=validDay?rawClosing:'';
 // Do not invent a cutoff from a serialized midnight. Omit only when the
 // calendar date has passed even in UTC-12; official closing terms govern.
 if(validDay&&day<new Date(now.getTime()-12*60*60*1000).toISOString().slice(0,10)){omitted++;continue;}
 const salaries=Array.isArray(d.PositionRemuneration)?d.PositionRemuneration.slice(0,5).map(x=>{const low=plain(x.MinimumRange,80),high=plain(x.MaximumRange,80),unit=plain(x.Description||x.RateIntervalCode,80);return [low&&high?`${low} - ${high}`:low||high,unit||'Pay period not provided'].filter(Boolean).join(' ');}):[];
 const details=d.UserArea?.Details;const paths=Array.isArray(details?.HiringPath)?details.HiringPath.filter(x=>typeof x==='string').map(x=>plain(x,120)).join(', '):'';
 jobs.push({id:plain(item.MatchedObjectId||d.PositionID,120)||url.split('/').filter(Boolean).pop(),title:plain(d.PositionTitle,240)||'Title not provided',agency:plain(d.OrganizationName,240)||'Agency not provided',location:plain(d.PositionLocationDisplay,400)||'Location not provided',salary:salaries.filter(Boolean).join('; ')||'Salary not provided',closingDate:closing||'Closing date not provided',whoMayApply:[plain(details?.WhoMayApply?.Name||d.WhoMayApply?.Name,1000),paths&&`Hiring path codes: ${paths}`].filter(Boolean).join(' | ')||'Who may apply not provided; check the announcement',qualifications:plain(d.QualificationSummary,3000)||'Qualifications not provided; check the announcement',url});
 }
 if(rows.length&&invalidLinks===rows.length)throw Error('invalid links');
 return {jobs,retrievedAt:now.toISOString(),source:'USAJOBS',scope:'public',...(omitted?{note:'Some returned announcements were omitted because their links were invalid or their closing dates had passed.'}:{})};
}
export function makeFederalJobsHandler({fetchImpl=fetch,env=()=>process.env,now=()=>new Date(),timeoutMs=8000}={}){return async req=>{
 const config=env(),available=config.TOPS_USAJOBS_ENABLED==='true'&&typeof config.USAJOBS_API_KEY==='string'&&!!config.USAJOBS_API_KEY.trim()&&typeof config.USAJOBS_USER_AGENT==='string'&&!!config.USAJOBS_USER_AGENT.trim();const u=new URL(req.url);
 if(req.method==='GET'&&u.search==='?config=1')return reply(200,{available,provider:'USAJOBS'});
 if(req.method!=='POST')return reply(405,{error:'method_not_allowed'});if(u.search)return reply(400,{error:'invalid_request'});if(req.headers.get('origin')!==u.origin)return reply(403,{error:'origin_rejected'});if(!available)return reply(503,{error:'federal_jobs_unavailable'});
 let input;try{if(!/^application\/json(?:\s*;|$)/i.test(req.headers.get('content-type')||''))throw Error();input=await readJSON(req,2048);if(!input||Array.isArray(input)||Object.keys(input).sort().join(',')!=='keyword,location'||!['keyword','location'].every(k=>typeof input[k]==='string'&&input[k].length<=(k==='keyword'?120:80)&&!/[\x00-\x1f\x7f<>]/.test(input[k]))||!input.keyword.trim()||!input.location.trim())throw Error();}catch{return reply(400,{error:'invalid_search'});}
 const target=new URL('https://data.usajobs.gov/api/search');for(const [k,v] of Object.entries({Keyword:input.keyword.trim(),LocationName:input.location.trim(),ResultsPerPage:'10',Page:'1',Fields:'Full',WhoMayApply:'Public'}))target.searchParams.set(k,v);
 const abort=new AbortController();let timer;try{return await Promise.race([(async()=>{const r=await fetchImpl(target.href,{headers:{Host:'data.usajobs.gov',Accept:'application/json','User-Agent':config.USAJOBS_USER_AGENT,'Authorization-Key':config.USAJOBS_API_KEY},redirect:'error',signal:abort.signal});if(r.status===429)return reply(429,{error:'federal_jobs_busy'});if(!r.ok)return reply(502,{error:'federal_jobs_unavailable'});const data=await readJSON(r,1048576);return reply(200,projectJobs(data,now()));})(),new Promise(resolve=>{timer=setTimeout(()=>{abort.abort();resolve(reply(504,{error:'federal_jobs_timeout'}));},Math.min(8000,timeoutMs));})]);}catch{return reply(abort.signal.aborted?504:502,{error:abort.signal.aborted?'federal_jobs_timeout':'federal_jobs_unavailable'});}finally{clearTimeout(timer);abort.abort();}
 };}
